### ISSUE TITLE
how can I use angularui-router?

### ISSUE THREAD

**Issue by redguardtoo** [forcedotcom/aura-ng#5]
as title?

besides? how can I use latest angular?

**Comment by dutchchasman** [comment]
I have just pushed a new version of the package to appexchange that has a new attribute on aurang:region called modules that you should be able to use.

Here is the install link:

https://login.salesforce.com/packaging/installPackage.apexp?p0=04to0000000GIRI

you should be able to change your region to look like this <aurang:region modules="ui.router">.

You'll also want to use <aurang:region scripts=> to include a reference to the angular-ui-router.js file (has to be stored in a static resource because of Lightning Components' current security restrictions).
